### ISSUE TITLE
Readme feedback

### ISSUE THREAD

**Issue by kathatherine** [anaconda/llm-eval#49]
This issue is to give feedback on the readme documentation for this repo, as requested. I have some punctuation/writing feedback and a few questions.

1. In the Using llm-eval section, the second sentence of the Eval concept, "Examples of checks include verifying if the response matches an exact value, contains specific content, includes code blocks, determining if those code blocks successfully, and validating..." - Should it be "determining if those code blocks successfully run"? Or something else?
2. In the Examples - Running Evals/Candidates from YAML files section, "results contains a list of lists of EvalResults. Each item in the outer list corresponds to a single Candidate and contains a list of EvalResults for all Evals ran against the Candidate." - The word "ran" should "run".
3. In the Installing - Environment Variables section, "HuggingFaceEndpointChata" appears to be a typo.
4. In the Development Environment Setup section, "The easiest way to setup the development environment..." - The word "setup" should be "set up".
5. In the Development Environment Setup - Managing Dependencies section, "Use the pip name in the when adding to either the dev_requirements.txt or the run_requirements.txt files." Seems like there's a missing word here.
6. And finally, this is probably just a lack of knowledge on my part, but how does a user know what options they have for defining Candidates and Evals using YAML files? Is there a dictionary of possible things one can put in these YAML files or is this just a standard YAML file thing anyone who would be using this would know about?

**Comment by shane-kercheval** [comment]
@kathatherine Thanks for the feedback!

1. Fixed (added `run`)
2. Fixed (ran -> run)
3. Fixed (removed `a` at the end)
4. Fixed (setup -> set up)
5. Fixed, reworded.
6. Good question and callout. The yamls (candidates/evals) all correspond to concrete python classes. The yaml structure and options correspond to fields of the corresponding class when instantiating the object (specifically, loading the yaml in as a dict, and then e.g. calling `Candidate.from_dict(...)`. But that's not clear in the documentation, and still forces the user to dig through code to figure out what options are available. I've added a separate issue to update the documentation https://github.com/anaconda/llm-eval/issues/50
